# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Cohen-Tanugi
email: david@embrlabs.com
description: > # this means to ignore newlines until "baseurl:"
  My name is David and I am a passionate innovator.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dctanugi.github.io" # the base hostname & protocol for your site
twitter_username: dctanugi
github_username:  dctanugi

# Build settings
markdown: kramdown
